export const enum BoardActionTypes {
    RESET_BOARD="RESET_BOARD",
    SET_ACTIVE_MODEL="SET_ACTIVE_MODEL",
    REMOVE_ACTIVE_MODEL="REMOVE_ACTIVE_MODEL",
    MOVE_MODEL="MOVE_MODEL",
    SET_CHECK="SET_CHECK",
    REMOVE_CHECK="REMOVE_CHECK",
    SET_MATE="SET_MATE",
    REMOVE_MATE="REMOVE_MATE",
    CHENGE_PLAYER="CHANGE_PLAYER"
}